sudo: required
language: java
jdk: oraclejdk8
dist: trusty
cache:
  directories:
    - '$HOME/.sonar/cache'
script:

skip_build:
- README.md：
- LICENSE
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
after_deploy:
- "./gradlew stest"

